= mbg-rename-plugin

== Overview
これはMyBatisGeneratorで生成する条件の名前を変更するためのプラグインです。 +

== Description
MyBatisGeneratorでは、CRUD操作で利用するテーブルに対する様々な条件を表すことができるExampleクラスというものを出力することができます。 +
しかし、Exampleという名称はあまりにも最終成果物としてふさわしくありません。 +
そこでExampleというクラス名を任意のクラス名に変更できるプラグインがMyBatisGeneratorのプラグインとして公開されていますが、メソッド名やその引数にいたるところまでは変更の対象として考えられていません。 +
このプラグインは既に存在するプラグインの内容を補完すべく以下の機能を有します。

- メソッド名の置換
- メソッドの引数名の置換
- メソッドの引数のアノテーションの属性値の置換
ｰ XMLマッパーに存在するExample/exampleの置換

上記を対応することで現状のMyBatisGeneratorでのExampleは消えることでしょう。


== How To Use
=== MyBatisGeneratorの設定ファイルの記述
このプラグインはMyBatisGeneratorが提供している名称変更プラグインと極力記述を同じようにするようにしました。

[source,XML]
----
<plugin type="com.zomu.t.mbg.rename.plugin.RenameExamplePlugin">
  <property name="searchString" value="Example"/> //<1>
  <property name="replaceString" value="Criteria"/> //<2>
  <property name="searchStringLower" value="example"/> //<3>
  <property name="replaceStringLower" value="criteria"/> //<4>
</plugin>
----

<1> 置換対象の文字列を指定。この指定はメソッド名の置換に利用されます。
<2> 置換する文字列を指定。この指定はメソッド名の置換に利用されます。
<3> 置換対象の文字列を指定。この指定は引数名、引数のアノテーションの属性値の置換に利用されます。
<4> 置換する文字列を指定。この指定は引数名、引数のアノテーションの属性値の置換に利用されます。

== How To Build
Gradleの単純なプロジェクトであるため、以下のコマンドでビルド可能です。 +
作成されたJarを利用してください。

[source,SH]
----
gradle clean build
----



